%%
christmas_bells = {...
    'Christ-', 'B'; 'mas', 'B'; 'bells', 'A';...
    'are', 'B'; 'ring-', 'G'; 'ing', 'D'; '', ''; '','';...
    'Hear', 'G'; 'what', 'F#'; '-', 'G';...
    'they', 'A'; '-', 'F#';...
    'say','G'; 'to','D'; 'you','D';...
    'Je-','G'; 'sus','F#'; '','G';...
    'is','A'; '','F#'; 'born','G'; '','E'; '','';...
    'in','C'; 'Beth','D'; '-','E'; 'le-','F#'; 'hem','G'; '','';'','';'','';...
    'In','G'; 'Beth','D'; '-','E'; 'le-','F#'; 'hem','G';...
    };
christmas_bells = christmas_bells(:,[2 1]);
%%
beautiful_savior = {...
    'D', 'Fair', 'Fair', 'Beau-'; '','','','';...
    'D', 'is', 'are', 'ti-'; 'D', 'the', 'the', 'ful'; 'E', 'sun', 'mead', 'Sav-';...
    'C#', '-', '-', '-'; 'D', 'shine','ows', 'ior';'','','','';...
    'F#', 'Fair', 'Fair', 'Lord'; '','','',''; 'F#', '-er', '-er', 'of'; 'F#', 'the', 'the', 'the';
    'G', 'moon', 'wood', 'na-'; 'E', '-', '-', '-'; 'F#', 'light', 'lands', 'tions';
    'A', 'And', 'Robed', 'Son'; '','','',''; 'D', 'all', 'in', 'of'; 'B', 'the', 'the', ''; 'A', 'stars', 'flow-', 'God'; '','','','';...
    'G', '', 'ers', ''; 'F#', 'in', 'of', 'and'; 'G', 'heav''n', 'bloom', 'Son'; '','','',''; 'F#', 'a -','ing', 'of'; '','','','';...
    'E', 'bove', 'spring', 'Man';'','','','';'','','','';...
    'A', 'Jes-','Jes-', 'Thee';'','','','';'B','sus','sus','will';'A','shines','is','I';'A','bright','fair','ho-';'F#','-','-','-';'G','ter','er','nor';'','','','';...
    'G','Jes-','Jes-','Praise';'','','','';'A','sus','sus','and';'G','shines','is','give';'G','pur','pur','glo-';'E','-','-','-';'F#','er','er','ry';...
    'F#','And','He','Give';'F#','brings','makes','praise';'F#','to','the','and';'A','all','sor-','glo-';'G','the','rowing','ry';...
    'F#','world','spir-','Ev-';'','','','';'E','his','it','er';'','','','';'D','love','sing','more';'','','','';...
    };

%% Happy Birthday
happy_birthday = {...
    'C','Hap';'C','py';'D','Birth';'C','day';'F','to';'E','you';'','';...
    'C','Hap';'C','py';'D','Birth';'C','day';'G','to';'F','you';'','';...
    'C','Hap';'C','py';'C2','Birth';'A','day';'F','dear';'E','___';'D','___';...
    'A#','Hap';'A#','py';'A','Birth';'F','day';'G','to';'F','you';'','';...
    };

%% Samuel Tells of the Baby Jesus
samuel_tells = {...
    'G','Said','A-';'C','Sam-','cross';'A#','-u-','the';'C','-el','sea';'','','';'D','With-','in';'C','in','Beth-';'A#','-','';'G','five','le-';'G','years','hem';'G','A','Lord';'F','night','Je-';'F','will','sus';'F','be','came';'D#','as','to';'G','day','earth';'','','';...
    'G','And','As';'C','Ba-','Sam-';'A#','-by','u-';'G','Je-','el';'F','-sus','had';'G','will','pro-';'F','-','-';'D#','be','phe-';'C','born','sied';'C','In','And';'D','a','';'D#','land','ang-';'G','far','els';'F','far','sang';'D#','','';'D','a-','His';'C','-way.','birth.';...
    'D','Ho-','';'D#','san-','';'','','';'D#','na!','';'F','Ho-','';'G','san-','';'A#','','';'A#','na!','';'','','';'A#','Oh','';'C','let','';'A#','us','';'G','glad-','';'A#','ly','';'F','sing','';'','','';'','','';...
    'F','How','';'D#','bless-','';'F','ed','';'G','that','';'A#','out','';'C','Lord','';'A#','was','';'G','born','';'','','';'A#','Let','';'G','earth','';'F','re-','';'D#','ceive','';'C','her','';'D#','King!','';...
    };
%% Kindness Begins with Me
be_kind = {...
    'C','I';'F','want';'F','to';'F','be';'A','kind';'F','to';'G','ev-';'A#','ry-';'D','one,';...
    'D','For';'E','that';'G','is,';'A#','right,';'D2','you';'C2','see.';'','';'','';'','';...
    'C','So';'C','I';'F','say';'F','to';'F','my-';'A','self,';'F','"Re-';'G','mem';'A#','ber';'D','this:';...
    'E','Kind-';'E','ness';'E','be-';'A#','gins';'E','with';'F','me."';...
    };
%% We Are Different
we_are_different = {...
    'E','I';'C','know';'G','you';'B','and';'B','you';'C','know';'A','me.';'','';'','';'','';'','';...
    'B','We';'B','are';'C','as';'D','dif-';'C','ferent,';'B','as';'A','the';'A','sun';'B','and';'A','the';'G','sea.';...
    'E','I';'C','know';'G','you';'B','and';'B','you';'C','know';'A','me.';'','';'','';'','';'','';...
    'B','And';'B','that''s,';'C','the';'D','way';'C','that';'B','it''s';'D','sup-';'D','posed';'C','to';'C','be.';...
    };
%% Love One Another
love_one_another = {...
    'F','As';'G','I';'A','have';'C','loved';'C','you,';'D','Love';'E','one';'F','an-';'D','oth';'D','-er.';...
    'G','This';'A','new';'A#','com-';'G','man';'G','-ment:';'F','Love';'E','one';'D','an-';'C','oth';'C','-er.';...
    'A','By';'A#','this';'C','shall';'A','men';'D','know';'G','Ye';'G','are';'A','my';'A#','dis-';'G','ci-';'G','ples,';...
    'F','If';'G','ye';'A','have';'F','love';'D','One';'E','to';'F','an-';'G','oth';'F','-er.';...
    };
%% I'm Trying to Be Like Jesus
be_like_jesus_verse = {...
    'C','I''m';'D','try-';'D#','ing';'F','to';'F','be';'C2','like';'A#','Je-';'','-';'D#','sus';'','';'','';...
    'D#','I''m';'D','fol-';'D#','low-';'F','ing';'G','in';'D#','his';'C','ways.';'','';'','';'','';'','';...
    'C','I''m';'D','try-';'D#','ing';'F','to';'F','love';'A#','as';'A#','he';'','-';'D#','did';'','';'','';...
    'D#','in';'D','all';'D#','that';'F','I';'G','do';'G','and';'A','say.';'','';'','';'','';'','';...
    'A','At';'A#','times';'A#','I am';'A','tempt-';'F','ed';'D','to';'G','make';'F','a';'D#','wrong';'F','choice';'','';...
    'F','But I';'G','try';'G','to';'A','list-';'F','en';'F','as the';'G','still';'A#','small';'C2','voice';'A#','whisp-';'C2','ers:';'','';'','';'','';'','';...
    };
be_like_jesus_chorus = {...
    'D2','Love';'D2','one an-';'D2','other-';'C2','er';'A#','as';'A#','Je-';'D#','sus';'G','loves';'F','you.';'','';...
    'G','Try';'A','to';'A#','show';'F','kind-';'A#','ness';'A#','in';'A#','all';'C2','that';'D2','you';'C2','do.';...
    'C2','Be';'D2','gen-';'D2','tle and';'D2','lov-';'C2','ing';'A#','in';'A#','deed';'A','and';'G','in';'F','thought,';...
    'D#','For';'D','these';'A#','are';'D','the';'D#','things';'C2','Je-';'A','sus';'A#','taught.';...
    };
%% Kindness Begins with Me
be_kind = {...
    'C','I';'F','want';'F','to';'F','be';'A','kind';'F','to';'G','ev-';'A#','ry-';'D','one,';...
    'D','For';'E','that';'G','is,';'A#','right,';'D2','you';'C2','see.';'','';'','';'','';...
    'C','So';'C','I';'F','say';'F','to';'F','my-';'A','self,';'F','"Re-';'G','mem';'A#','ber';'D','this:';...
    'E','Kind-';'E','ness';'E','be-';'A#','gins';'E','with';'F','me."';...
    };
%% Hark the Herald Angels Sing
hark_the_herald = {...
    'C','Hark';'F','the';'F','her-';'E','ald';'F','an-';'A','gels';'A','sing-';'G','-';'C','glo-,';...
    'C','ry';'C','to';'A#','the,';'A','new-,';'G','born';'A','king';...
    'C','Peace';'F','on';'F','earth';'E','and';'F','mer-';'A','cy';'A','mi-';'G','ld';'C','God';...
    'G','and';'G','sin-';'E','ners';'E','re-,';'D','con-';'C','ciled';...
    'C','Joy-';'C','ful';'C','all';'F','ye';'A#','na-';'A','tions';'A','ri-';'G','se';'','';'','';'','';'','';'','';'','';'','';...
    'C','Join';'C','the';'C','tri-';'F','umph';'A#','of';'A','the';'A','ski-';'G','es';'','';'','';'','';'','';'','';'','';'','';...
    'D','With';'D','th an-';'D','gel-';'C','ic';'A#','hosts';'A','pro-';'A#','claim';...
    'G','Christ';'A','is-';'A#','-';'C','born';'F','in';'F','Beth-';'G','le-';'A','hem';...
    'D','Hark';'D','the';'D','her-';'C','ald';'A#','an-';'A','gels';'A#','sing';...
    'G','Christ';'A','is-';'A#','-';'C','born';'F','in';'F','Beth-';'G','le-';'F','hem';...
    };
%% Away in a Manger
away_in_a_manger = {...
    'C','A-';'F','way';'F','in';'G','a-';'A','-';'F','man-';'F','ger';'A','No-';'A#','-';'C','crib';'C','for';'D','a';'A#','bed';...
    'G','The-';'A','-';'A#','lit-';'A#','tle';'C','Lord';'A','Je-';'A','sus';'F','lay-';'A','-';'G','down';'D','his';'F','sweet';'E','head';...
    'C','The';'F','stars';'F','in';'G','the-';'A','-';'F','hea-';'F','vens';'A','Looked-';'A#','-';'C','down';'C','where';'D','he';'A#','lay';...
    'G','The-';'A','-';'A#','lit-';'A#','tle';'C','Lord';'A','Je-';'A','sus';'F','a-';'A','-';'G','sleep';'D','on';'E','the';'F','hay';...
    };
%% Silent Night
silent_night = {...
    'F','Si-';'G','-';'F','lent';'D','night';'','';...
    'F','Ho-';'G','-';'F','ly';'D','night';...
    'C','All';'C','is';'A','calm,';'','';'A#','All';'A#','is';'F','bright';'','';'','';...
    'G','Round';'G','yon';'A#','vir-,';'A','-';'G','gin';'F','mo-';'G','ther';'F','and';'D','Child';...
    'G','Ho-';'G','ly';'A#','in-,';'A','fant';'G','so';'F','ten-';'G','der';'F','and';'D','mild';...
    'C','Sleep';'C','in';'D#','hea-,';'C','ven-';'A','ly';'A#','pea-';'D','ce';'','';'','';...
    'A#','Sle-';'F','ep';'D','in';'F','hea-,';'D#','ven-';'C','ly';'A#','peace';...
    };
% song = love_one_another;
% title = 'Love One Another';
% x_max = 13;
% song = we_are_different;
% title = 'We Are Different';
% x_max = 14;
% song = hark_the_herald;
% title = 'Hark the Herald Angels Sing';
% x_max = 19;
% song = away_in_a_manger;
% title = 'Away in a Manger';
% x_max = 17;
song = silent_night;
title = 'Silent Night';
x_max = 12;
% song = beautiful_savior;
% title = 'Beautiful Savior';
% x_max = 19;
% song = happy_birthday;
% title = 'Happy Birthday';
% x_max = 9;
% song = samuel_tells;
% title = 'Samuel Tells of the Baby Jesus';
% x_max = 21;
% song = be_like_jesus_verse;
% title = 'I''m Trying to Be Like Jesus (Verse)';
% x_max = 14;
% song = be_like_jesus_chorus;
% title = 'I''m Trying to Be Like Jesus (Chorus)';
% x_max = 13;
%%
note_color_map = {'D2', [255 106 0];...
                  'C2', [190 0 0];...
                  'B',  [146 0 108];...
                  'A#', [13 152 240];...
                  'A',  [0 0 153];...
                  'G#', [51 204 204];...
                  'G',  [0 205 200];...
                  'F#', [6 250 99];...%[116 208 125]
                  'F',  [0 152 0];...
                  'E',  [255 192 0];...
                  'D#', [250 120 74];...
                  'D',  [255 106 0];...
                  'C#', [223 52 92];...
                  'C',  [238 0 0];...
                  };
%%
figure
set(gcf,'Position',[15 220 75*(x_max+1) 75*10]);
titleh = text(1.5,11.25,title,'FontSize',20, 'VerticalAlignment','bottom');
axis equal
set(gca,'XLim',[-1 x_max+1], 'YLim', [0 12]);
e=get(titleh,'Extent');
tpos = get(titleh,'Position');
adj = x_max/2 - tpos(1) - e(3)/2;
set(titleh,'Position',tpos+[adj 0 0]);
set(gca,'XTick',[],'YTick',[]);
set(gca,'XColor','white','YColor','white')
set(gca,'Position',[.02 .02 .96 .96])
%%
start_position = 0;
if size(song,2)==2
    delta_y = 1.8;
elseif size(song,2)==3
    delta_y = 2.3;
elseif size(song,2)==4
    delta_y = 2.35;
else
    fprintf('Too many verses?');
end
y = 11.2-delta_y;
note_dy = .2 + 0.3*(size(song,2)-1);
%%
for i=1:size(song,1)
    note = song{i,1};
    if isempty(note)
        start_position = start_position+1.25;
        if start_position > x_max-1
            start_position = 0;
            y = y - delta_y;
        end
        continue;
    end
    %%
    note_color = note_color_map{strcmp(note,note_color_map(:,1)),2}./255;
    if length(note)>1
        rh = rectangle('Position', [start_position y+note_dy 1 1], 'Curvature', [1 1 ], 'EdgeColor', 'k', 'LineWidth', 5, 'FaceColor', note_color);
        txt_offset = 0.25;
    else
        rh = rectangle('Position', [start_position y+note_dy 1 1], 'Curvature', [1 1 ], 'FaceColor', note_color);
        txt_offset = 0.32;
    end

    th = text(start_position,y,song(i,2:end), 'Color','black','FontSize', 14, 'VerticalAlignment','bottom', 'HorizontalAlignment','center');

    e = get(th,'Extent');
    over = (e(1) + e(3)/2) - (start_position+1/2);
    if over >= 0
        set(rh,'Position',[start_position+over y+note_dy 1 1]);
    else
        set(th,'Position',[start_position-over y 0]);
    end
    rpos = get(rh,'Position');
    text(rpos(1)+txt_offset,y+.5+note_dy,note,'Color','white','FontSize',20);
    start_position = max(start_position+1,e(1)+e(3)) + 0.25;
    if start_position > x_max-1
        start_position = 0;
        y = y - delta_y;
    end
end
